# TODO UPDATE DOCS WHEN UPDATE PNPM
# https://pnpm.io/es/8.x/docker

# Stage 1 - base
FROM node:20.12.2 AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Stage 2 - the build process
FROM base AS build
WORKDIR /usr/src/app

# pnpm fetch does require only lockfile
COPY pnpm-lock.yaml .
RUN pnpm fetch

COPY .npmrc package.json ./
RUN pnpm install --offline --ignore-scripts --frozen-lockfile

ADD . ./

RUN pnpm exec nx run @kinkoi/api:build
RUN pnpm deploy --filter=@kinkoi/api --prod /prod/api

# API APP
FROM base AS api

COPY --from=build /prod/api /prod/api
WORKDIR /prod/api

CMD [ "pnpm", "run", "start:prod"]
