version: "3.8"
services:
    api:
        build:
            context: .
            target: api
        ports:
            - "8080:8080"
        #environment:
        #- PNPM_HOME="/pnpm"
        #- PATH="$PNPM_HOME:$PATH"
        volumes:
            - ./apps/api:/prod/api
            - /apps/api/node_modules

    kinkoi-dashboard:
        build:
            context: .
            target: kinkoi-dashboard
        ports:
            - "4321:4321"
        #environment:
        #- HOST=0.0.0.0
        #- PORT=4321
        #- PNPM_HOME="/pnpm"
        #- PATH="$PNPM_HOME:$PATH"
        volumes:
            - ./apps/dashboard:/prod/kinkoi-dashboard
            - /apps/dashboard/node_modules
            - /node

volumes:
    api-data:
    kinkoi-dashboard-data:
