name: ci-kinkoi-api

on:
    push:
        paths:
            - "apps/api/**"
            - "*.*"
        branches:
            - main
    pull_request:
        paths:
            - "apps/api/**"
            - "*.*"

# Needed for nx-set-shas when run on the main branch
permissions:
    actions: read
    contents: read

jobs:
    main:
        runs-on: ubuntu-latest

        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

        steps:
            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
              with:
                  fetch-depth: 0

            - name: Setup Nodejs
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
              with:
                  node-version: 20.12.2

            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 9.0.6

            - name: Restore cached npm dependencies
              id: cache-dependencies-restore
              uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
              with:
                  path: |
                      node_modules
                      ~/.cache/Cypress # needed for the Cypress binary
                  key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}

            - name: Install monorepo dependencies
              run: pnpm install --frozen-lockfile

            - name: Cache npm dependencies
              id: cache-dependencies-save
              uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
              with:
                  path: |
                      node_modules
                      ~/.cache/Cypress # needed for the Cypress binary
                  key: ${{ steps.cache-dependencies-restore.outputs.cache-primary-key }}

            # --distribute-on="5 linux-medium-js"
            - name: Start Nx Cloud
              run: pnpm exec nx-cloud start-ci-run --stop-agents-after="build" --use-dte-by-default=false

            - name: Set Nx SHA
              uses: nrwl/nx-set-shas@76907e7e5d3cd17ddb5e2b123389f054bffcdd03 # v4

            # This line is needed for nx affected to work when CI is running on a PR
            - name: Set track branch for nx affected (PR ONLY)
              if: ${{ github.event_name == 'pull_request' }}
              run: git branch --track main origin/main

            - name: Execute lint test and build for affected files (PR ONLY)
              if: ${{ github.event_name == 'pull_request' }}
              run: pnpm exec nx affected -t lint test build --files=apps/api

            - name: Execute lint test and build for affected files (PR ONLY)
              if: ${{ github.event_name == 'push' }}
              run: pnpm exec nx run-many -p @kinkoi/api -t lint test build

            - name: Upload API coverage reports to Codecov
              uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4
              with:
                  directory: ./apps/api/coverage
                  files: ./lcov.info
                  flags: kinkoi/api
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: pabloimrik17/kinkoi-project
